/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { FlightGet$Plain$Params } from './fn/flight/flight-get-plain';
export { flightGet$Plain } from './fn/flight/flight-get-plain';
export type { FlightGet$Params } from './fn/flight/flight-get';
export { flightGet } from './fn/flight/flight-get';
