/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { BookingRm } from '../models/booking-rm';
import { cancelBooking } from '../fn/booking/cancel-booking';
import { CancelBooking$Params } from '../fn/booking/cancel-booking';
import { listBooking } from '../fn/booking/list-booking';
import { ListBooking$Params } from '../fn/booking/list-booking';
import { listBooking$Plain } from '../fn/booking/list-booking-plain';
import { ListBooking$Plain$Params } from '../fn/booking/list-booking-plain';

@Injectable({ providedIn: 'root' })
export class BookingService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listBooking()` */
  static readonly ListBookingPath = '/Booking/{email}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listBooking$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  listBooking$Plain$Response(params: ListBooking$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<BookingRm>>> {
    const obs = listBooking$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listBooking$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listBooking$Plain(params: ListBooking$Plain$Params, context?: HttpContext): Promise<Array<BookingRm>> {
    const resp = this.listBooking$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<BookingRm>>): Array<BookingRm> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listBooking()` instead.
   *
   * This method doesn't expect any request body.
   */
  listBooking$Response(params: ListBooking$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<BookingRm>>> {
    const obs = listBooking(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listBooking$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listBooking(params: ListBooking$Params, context?: HttpContext): Promise<Array<BookingRm>> {
    const resp = this.listBooking$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<BookingRm>>): Array<BookingRm> => r.body);
  }

  /** Path part for operation `cancelBooking()` */
  static readonly CancelBookingPath = '/Booking';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `cancelBooking()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  cancelBooking$Response(params?: CancelBooking$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = cancelBooking(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `cancelBooking$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  cancelBooking(params?: CancelBooking$Params, context?: HttpContext): Promise<void> {
    const resp = this.cancelBooking$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
