/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { flightGet } from '../fn/flight/flight-get';
import { FlightGet$Params } from '../fn/flight/flight-get';
import { flightGet$Plain } from '../fn/flight/flight-get-plain';
import { FlightGet$Plain$Params } from '../fn/flight/flight-get-plain';
import { FlightRm } from '../models/flight-rm';

@Injectable({ providedIn: 'root' })
export class FlightService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `flightGet()` */
  static readonly FlightGetPath = '/Flight';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `flightGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  flightGet$Plain$Response(params?: FlightGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<FlightRm>>> {
    const obs = flightGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `flightGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  flightGet$Plain(params?: FlightGet$Plain$Params, context?: HttpContext): Promise<Array<FlightRm>> {
    const resp = this.flightGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<FlightRm>>): Array<FlightRm> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `flightGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  flightGet$Response(params?: FlightGet$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<FlightRm>>> {
    const obs = flightGet(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `flightGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  flightGet(params?: FlightGet$Params, context?: HttpContext): Promise<Array<FlightRm>> {
    const resp = this.flightGet$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<FlightRm>>): Array<FlightRm> => r.body);
  }

}
