/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { FlightRm } from '../models/flight-rm';
import { searchFlight } from '../fn/flight/search-flight';
import { SearchFlight$Params } from '../fn/flight/search-flight';
import { searchFlight$Plain } from '../fn/flight/search-flight-plain';
import { SearchFlight$Plain$Params } from '../fn/flight/search-flight-plain';

@Injectable({ providedIn: 'root' })
export class FlightService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `searchFlight()` */
  static readonly SearchFlightPath = '/Flight';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchFlight$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchFlight$Plain$Response(params?: SearchFlight$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<FlightRm>>> {
    const obs = searchFlight$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchFlight$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchFlight$Plain(params?: SearchFlight$Plain$Params, context?: HttpContext): Promise<Array<FlightRm>> {
    const resp = this.searchFlight$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<FlightRm>>): Array<FlightRm> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchFlight()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchFlight$Response(params?: SearchFlight$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<FlightRm>>> {
    const obs = searchFlight(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchFlight$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchFlight(params?: SearchFlight$Params, context?: HttpContext): Promise<Array<FlightRm>> {
    const resp = this.searchFlight$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<FlightRm>>): Array<FlightRm> => r.body);
  }

}
